version: "3.3"

services:

    application:
        build: .
        container_name: nginx-nest-react
        restart: always
        ports:
        - "80:80"
        - "443:443"
        - "3000"
        volumes:
        - ./public:/www/public

networks:
    default:
      driver: bridge